### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by electr0de** [fishyboteso/fishyboteso#126]
Need to create automatic publish when a new version tag is assigned.

**Comment by SemjonWilke** [comment]
+1

**Comment by adsau59** [comment]
done

frontend:
ca06141386fe2d1d602001420145a220d17a8a9e
0fef4aa22cf733de8d1973564ae8a1b47a669de7
cc926bf5fda78a3f9410ecc63c8ac0b17a0cfaab

backend:
https://github.com/fishyboteso/fishy-web/issues/8

**Comment by adsau59** [comment]
now update is published automatically whenever version.txt is updated
