### ISSUE TITLE
Not all addon dependencies are installed

### ISSUE THREAD

**Issue by adsau59** [fishyboteso/fishyboteso#127]
![image](https://user-images.githubusercontent.com/10076396/177012862-88baf584-afe4-4fa9-903d-c8ab01bf48b8.png)

when FishyQR is installed, there are some dependencies which are missing for it to work....

Work around for now:
install them manually

**Comment by SemjonWilke** [comment]
![grafik](https://user-images.githubusercontent.com/1882648/177192926-d0945830-bc3a-4a57-bd30-4a0f7176e741.png)
