### ISSUE TITLE
Exception in splash screen on first launch

### ISSUE THREAD

**Issue by adsau59** [fishyboteso/fishyboteso#129]
![20220702_010140](https://user-images.githubusercontent.com/10076396/177013035-148132cf-0ec9-46e1-baaa-82d67c3f85a6.jpg)

no effect on behavior as far as I saw, just the exception

**Comment by adsau59** [comment]
related https://github.com/fishyboteso/fishyboteso/pull/123

**Comment by SemjonWilke** [comment]
can't reproduce
