### ISSUE TITLE
use different config json when test flag is used

### ISSUE THREAD

**Issue by adsau59** [fishyboteso/fishyboteso#135]
### Motivations:
currently switching back and from test/live server causes the bot to renew uid again and again, which pollutes the db for no reason. to resolve this issue, we can make the bot use different config when `--test-server` flag is used  

### Requirements:
if `--test-server` cli parameter is used, use `fishy_config_test.json` file to load the config, if not use the default `fishy_config.json` file

**Comment by shayaan245** [comment]
Done
