### ISSUE TITLE
name incorrect for saving images in debug option

### ISSUE THREAD

**Issue by adsau59** [fishyboteso/fishyboteso#158]
![image](https://user-images.githubusercontent.com/10076396/235059922-ed5a4c35-896a-4fc9-b3bd-7927891a367f.png)

it says show grab window instead

**Comment by harshil202** [comment]
So what name you would like to put there?

**Comment by adsau59** [comment]
fixed in https://github.com/fishyboteso/fishyboteso/pull/163
