### ISSUE TITLE
"Sound Notification" option does not toggle beep sound

### ISSUE THREAD

**Issue by SemjonWilke** [fishyboteso/fishyboteso#161]
STR:
- launch fishy
- switch to semi auto engine
- go into config
- make sure `Sound Notification` option is disabled
- use f9 key to start the bot
- notice you can hear the beep sound

Expected:
- beep sound shouldn't occur if `Sound Notification` is disabled

**Comment by MaxurDev** [comment]
Could you provide some more info on the Sound Notification option, I might try to make a PR for it

**Comment by shayaan245** [comment]
STR not mentioned please provide some STR @adsau59

**Comment by adsau59** [comment]
@shayaan245 str provided please check description

**Comment by shayaan245** [comment]
Done
