### ISSUE TITLE
create a warning dialogue for "save screenshots"

### ISSUE THREAD

**Issue by adsau59** [fishyboteso/fishyboteso#162]
when save screenshots is enabled, show a warning message saying that it'll save in documents

and when it is disabled, ask if they want to delete the saved screenshots or not

**Comment by adsau59** [comment]
its toggled over [here](https://github.com/adsau59/fishyboteso/blob/5fe4c235ac8e6b029c5f809a04d713f5a2e5c084/fishy/gui/main_gui.py#L86-L96)

**Comment by BDadmehr0** [comment]
I have adjusted and established the conditions and I think this is the solution, I will submit the changes in a pull request.

**Comment by adsau59** [comment]
resolved in https://github.com/fishyboteso/fishyboteso/pull/163
