### ISSUE TITLE
Notification always on

### ISSUE THREAD

**Issue by SemjonKerner** [fishyboteso/fishyboteso#22]
The bot is always notifying me on discord, as long as i am logged in, ignoring the state of the "notification" checkbox in configs.

(Also it is giving false "Hole depleted" very often. Sometimes after every other fish. ~~But this might be a side effect of #19~~)

**Comment by adsau59** [comment]
i think that issue is cuz of backend, will check  and let u know

**Comment by SemjonKerner** [comment]
I hope not. Backend shouldn't even be informed if the user doesn't want to.

**Comment by SemjonKerner** [comment]
Could you reproduce it tho?

**Comment by SemjonKerner** [comment]
Trying to uncheck "Notifications" after 0.4.4:
```
Traceback (most recent call last):
  File "C:\Users\coma\Documents\GitHub\fishyboteso\fishy\web\decorators.py", line 25, in wrapper
    return f(*args, **kwargs)
TypeError: is_subbed() takes 0 positional arguments but 1 was given
```

**Comment by SemjonKerner** [comment]
fixed with last backend update
