### ISSUE TITLE
Window server thread keeps running when main gui exits

### ISSUE THREAD

**Issue by SemjonKerner** [fishyboteso/fishyboteso#31]
https://github.com/adsau59/fishyboteso/blob/3a6f29b642da6d2f5e8856f4566c89a385e051f6/fishy/engine/common/window_server.py#L72

In certain cases the window server thread won't stop with the other threads, because it has no knowledge of their states.
The Window server thread must always end when the main gui thread ends.

I would suggest using a shared list of thread PIDs and un-/register every thread on start/end. So that the main thread can kill every zombie thread on exit.

**Comment by adsau59** [comment]
said issue is fixed in v0.5.7

but, `shared list of thread PIDs and un-/register every thread on start/end is a great idea`, closing this issue for now and creating a new one for it

**Comment by adsau59** [comment]
created https://github.com/fishyboteso/fishyboteso/issues/104
