### ISSUE TITLE
input lag with fishy engine running

### ISSUE THREAD

**Issue by SemjonKerner** [fishyboteso/fishyboteso#35]
There is significant input lag with fishy engine running. This is probably caused by the keyboard library, used to send key strokes to the game.

**Comment by SemjonKerner** [comment]
> optimize hotkey using multiprocess to fix input lag

Copied from Trello

**Comment by adsau59** [comment]
done in https://github.com/fishyboteso/fishyboteso/pull/77, will be fixed in 0.4.10
