### ISSUE TITLE
Requesting few changes for update popup feature

### ISSUE THREAD

**Issue by adsau59** [fishyboteso/fishyboteso#42]
1. Popup comes up before the UI loads, which might confuse the user thinking, "why isn't fishybot starting". To keep it consistent with other software design we use like vlc, sourcetree, vscode... we should ask the user after the ui is done loading
2. Popups in fishy should follow the theme of the application like how config popups do

Edit Fixed with #47:
~~2. The icon in the popup is the default tkinter logo which looks weird, use fishy logo to keep the ui consistent~~
~~3. The "No" button looks more attractive as its bright red, in contrast to light green color of the "Yes" button. Which might cause user to press "No" rather than "Yes". Maybe make the "No" a bit dull in color, or atleast keep it the same so the user can make the choice what they want, rather than clicking what looks attractive.~~

**Comment by anivr1n** [comment]
Can you do switch weapon command on bot? It helps staying all the times on 1 spot till spot respawn.

**Comment by adsau59** [comment]
@anivr1n pls create a new issue for a new feature request

**Comment by adsau59** [comment]
> Can you do switch weapon command on bot? It helps staying all the times on 1 spot till spot respawn.

@anivr1n  pls create a new issue for a new feature request

**Comment by adsau59** [comment]
fixed in v0.5.7
