### ISSUE TITLE
Icon in the task bar shows python window instead of fishy logo

### ISSUE THREAD

**Issue by adsau59** [fishyboteso/fishyboteso#64]
![image](https://user-images.githubusercontent.com/10076396/114871193-a898fe00-9e16-11eb-8229-72969ce07ca1.png)

**Comment by SemjonKerner** [comment]
![grafik](https://user-images.githubusercontent.com/1882648/114892110-c2354800-9e0c-11eb-8546-f16468283f83.png)
How to reproduce?

**Comment by adsau59** [comment]
oh, also, it does that when you run the bot using the command instead of logo
