### ISSUE TITLE
Full auto engine doesn't let me controll my mouse

### ISSUE THREAD

**Issue by adsau59** [fishyboteso/fishyboteso#79]
work around: Press CTRL+SHIFT+ESC to open task manager, and end the python/fishy processes. That way fishy will be forced to close and it'll stop operating ur mouse/keyboard.

**Comment by wabkia** [comment]
Changes made in #90 eliminate this bug. Alt tab shows 3 quit messages as soon as the tab out event happens. I’m unsure of which change individually contributed to this but as I was working on it I went through many variations of this bug.
