### ISSUE TITLE
human-like delay is too slow

### ISSUE THREAD

**Issue by adsau59** [fishyboteso/fishyboteso#81]
users have complained human-like delay is too slow, even manual fishing is faster than that

**Comment by adsau59** [comment]
![image](https://user-images.githubusercontent.com/10076396/118384352-0fcaed80-b623-11eb-83ed-283ae9d27d87.png)

**Comment by SemjonKerner** [comment]
+1

**Comment by SemjonKerner** [comment]
will be fixed together with #105
