### ISSUE TITLE
bot starts fishing when i start recording

### ISSUE THREAD

**Issue by Ronso20** [fishyboteso/fishyboteso#82]
The bot starts fishing when i start recording and i'm looking at fishing hole at that moment.

**Comment by adsau59** [comment]
not able to reproduce this issue, do you have any steps to reproduce this issue?

**Comment by Ronso20** [comment]
https://youtu.be/nfq1ucca-Y8

But, it's not really a big problem, i can just look away and then start recording.

**Comment by adsau59** [comment]
fixed in v0.5.7
