### ISSUE TITLE
doesn't work after ReShade install??

### ISSUE THREAD

**Issue by FieldForest** [fishyboteso/fishyboteso#93]
Don't know if this got an connection but ever since i installed a ReShade mod this doesn't work?
i've tried to remove the ReShade in the install dictionary, but that didnt work..

**Comment by FieldForest** [comment]
Nvm... I uninstalled completely and it worked again..

**Comment by SemjonKerner** [comment]
This is already covered in the Wiki. See 5:
https://github.com/fishyboteso/fishyboteso/wiki/When-fishy-won't-work
